### ISSUE TITLE
intl 0.17.0

### ISSUE THREAD

**Issue by yuriescl** [yamarkz/postal_code_jp#6]
Please upgrade dependency `intl` to version `^0.17.0`

**Comment by yamarkz** [comment]
ok

**Comment by yuriescl** [comment]
Thanks!
The change appears on master branch but I don't see it on pub.dev

**Comment by yamarkz** [comment]
I'm working on refactoring the code.
It will be released over the weekend, so please wait.

**Comment by yamarkz** [comment]
I published version 1.1.0. It contains update package intl 0.17.0.
